"""Type, identity and sequence mappings to PostgreSQL (Sprint 9 Step 1a).

The decisions are SYNTHESIS P1-A's, and the owner's (2026-09-30):

* ``money`` → ``NUMERIC(19, 4)``, ``smallmoney`` → ``NUMERIC(10, 4)``, and
  ``bit`` → ``BOOLEAN``, with 0 and 1 in its defaults and CHECKs written FALSE
  and TRUE. Each is exact, so none is a gap;
* ``hierarchyid`` → ``LTREE`` and ``geography`` → PostGIS ``GEOGRAPHY``, only
  when the export says the target has the extension, and the file then starts
  with ``CREATE EXTENSION IF NOT EXISTS``. Otherwise each is a named gap;
* an identity column keeps its seed and increment, as ``GENERATED BY DEFAULT
  AS IDENTITY`` on an integer type and as a sequence default (named) on any
  other; a column an Oracle trigger fills from a sequence is a named gap;
* a PostgreSQL model's sequences are created, and its ``nextval`` defaults
  kept.

These assert what the export says, parsed back into a tree. What PostgreSQL
does with it is ``test_type_mappings_on_postgres``. Negative controls: removing
a mapping makes the column a named gap, never a silent TEXT; an importer that
loses identity columns or sequences fails the independent count below.
"""

from __future__ import annotations

import logging
import re
import uuid
from collections.abc import AsyncIterator
from pathlib import Path

import pytest
import pytest_asyncio
import sqlglot
from sqlalchemy import Uuid, bindparam, text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker
from sqlglot import exp

from app.models.metadata_store import Base, DataModel, Workspace
from app.schemas.data_model import SynthesizedModel
from app.services import ddl_export
from app.services.ddl_import import importer
from app.services.ddl_import.importer import import_ddl
from app.services.exporter_service import ExporterError, ExporterService
from app.services.graph_repository import GraphRepository
from app.services.synthesis_engine import SynthesisEngine
from tests._test_db import make_test_engine

logging.getLogger("sqlglot").setLevel(logging.CRITICAL)

FIXTURES = Path(__file__).resolve().parent / "fixtures"
MAPPINGS = FIXTURES / "ddl_mappings"
GENUINE = FIXTURES / "ddl"
BOTH = frozenset({"ltree", "postgis"})


def _import(dialect: str, path: Path) -> SynthesizedModel:
    result = import_ddl(path.read_bytes(), dialect, path.name)
    assert result.status == "reconciled" and result.model is not None, result.report["failures"][:3]
    return result.model


def _mapping_case(dialect: str) -> SynthesizedModel:
    stem = {"tsql": "type_mappings", "oracle": "identity", "postgres": "sequences"}[dialect]
    return _import(dialect, MAPPINGS / dialect / f"{stem}.sql")


def _export(model: SynthesizedModel, source: str, extensions: frozenset[str] = frozenset()) -> ddl_export.DdlExport:
    return ExporterService(source_dialect=source).generate_ddl_export(model, "postgres", extensions)


def _column(export: ddl_export.DdlExport, table: str, column: str) -> exp.ColumnDef:
    for statement in export.statements:
        tree = sqlglot.parse_one(statement, read="postgres")
        if isinstance(tree, exp.Create) and isinstance(tree.this, exp.Schema) and tree.this.this.name == table:
            return next(c for c in tree.this.expressions if isinstance(c, exp.ColumnDef) and c.name == column)
    raise AssertionError(f"no table {table} in the export")


def _type(export: ddl_export.DdlExport, table: str, column: str) -> str:
    return _column(export, table, column).args["kind"].sql("postgres")


def _gaps_naming(export: ddl_export.DdlExport, table: str, column: str) -> list[ddl_export.ExportGap]:
    return [g for g in export.gaps if g.entity == table and g.detail.split(" ", 1)[0].rstrip(":") == column]


# --- Plain mappings -----------------------------------------------------------------

def test_money_smallmoney_and_bit_are_exact_and_not_gaps() -> None:
    export = _export(_mapping_case("tsql"), "tsql")
    assert (_type(export, "Ledger", "Amount"), _type(export, "Ledger", "Fee")) == ("DECIMAL(19, 4)", "DECIMAL(10, 4)")
    assert (_type(export, "Ledger", "IsActive"), _type(export, "Ledger", "IsVoid")) == ("BOOLEAN", "BOOLEAN")
    defaults = [_column(export, "Ledger", c).find(exp.DefaultColumnConstraint).this.sql("postgres")
                for c in ("IsActive", "IsVoid")]
    assert defaults == ["TRUE", "FALSE"]
    for column in ("Amount", "Fee", "IsActive", "IsVoid"):
        assert _gaps_naming(export, "Ledger", column) == []


def test_a_check_over_bit_columns_compares_with_false_and_true() -> None:
    export = _export(_mapping_case("tsql"), "tsql")
    ledger = next(sqlglot.parse_one(s, read="postgres") for s in export.statements if '"Ledger"' in s[:40])
    checks = {c.this.sql("postgres") for c in ledger.find_all(exp.CheckColumnConstraint)}
    assert '"IsVoid" = FALSE OR "IsActive" = FALSE' in {re.sub(r"[()]", "", c).strip() for c in checks}


# --- Extension-backed mappings ------------------------------------------------------

def test_without_the_options_hierarchyid_and_geography_are_named_gaps() -> None:
    export = _export(_mapping_case("tsql"), "tsql")
    assert (_type(export, "Batch", "Node"), _type(export, "Batch", "Location")) == ("VARCHAR", "TEXT")
    assert "target_has_ltree" in _gaps_naming(export, "Batch", "Node")[0].detail
    assert "target_has_postgis" in _gaps_naming(export, "Batch", "Location")[0].detail
    assert not any(s.startswith("CREATE EXTENSION") for s in export.statements), "no extension is assumed"


def test_with_the_options_they_map_and_the_file_creates_the_extensions_first() -> None:
    export = _export(_mapping_case("tsql"), "tsql", BOTH)
    assert export.statements[:2] == ["CREATE EXTENSION IF NOT EXISTS ltree", "CREATE EXTENSION IF NOT EXISTS postgis"]
    assert (_type(export, "Batch", "Node").upper(), _type(export, "Batch", "Location")) == ("LTREE", "GEOGRAPHY")
    assert _gaps_naming(export, "Batch", "Node") == _gaps_naming(export, "Batch", "Location") == []


def test_each_option_maps_only_its_own_type() -> None:
    export = _export(_mapping_case("tsql"), "tsql", frozenset({"ltree"}))
    assert _type(export, "Batch", "Node").upper() == "LTREE"
    assert _type(export, "Batch", "Location") == "TEXT" and _gaps_naming(export, "Batch", "Location")
    assert [s for s in export.statements if s.startswith("CREATE EXTENSION")] == ["CREATE EXTENSION IF NOT EXISTS ltree"]


def test_an_extension_option_for_another_target_is_refused() -> None:
    with pytest.raises(ExporterError, match="PostgreSQL export only"):
        ExporterService(source_dialect="tsql").generate_ddl_export(_mapping_case("tsql"), "snowflake", BOTH)
    with pytest.raises(ExporterError, match="unknown target extension"):
        ExporterService(source_dialect="tsql").generate_ddl_export(_mapping_case("tsql"), "postgres",
                                                                     frozenset({"timescaledb"}))


# --- Negative controls: a removed mapping is a named gap, never a silent TEXT -------

_MAPPED = {  # the fixture column each mapping applies to
    "MONEY": ("Ledger", "Amount"), "SMALLMONEY": ("Ledger", "Fee"), "BIT": ("Ledger", "IsActive"),
    "HIERARCHYID": ("Batch", "Node"), "GEOGRAPHY": ("Batch", "Location"),
}


def test_every_mapping_has_a_case_in_the_fixture() -> None:
    assert sorted(m.type for m in ddl_export.TYPE_MAPPINGS) == sorted(_MAPPED)


@pytest.mark.parametrize("mapping", ddl_export.TYPE_MAPPINGS, ids=lambda m: m.type)
def test_negative_control_without_the_mapping_the_column_is_a_named_gap(
    mapping: ddl_export.TypeMapping, monkeypatch: pytest.MonkeyPatch
) -> None:
    table, column = _MAPPED[mapping.type]
    mapped = _export(_mapping_case("tsql"), "tsql", BOTH)
    assert _gaps_naming(mapped, table, column) == [], "fixture sanity: the mapping applies"
    monkeypatch.setattr(ddl_export, "TYPE_MAPPINGS", tuple(m for m in ddl_export.TYPE_MAPPINGS if m != mapping))
    unmapped = _export(_mapping_case("tsql"), "tsql", BOTH)
    gaps = _gaps_naming(unmapped, table, column)
    assert len(gaps) == 1 and gaps[0].kind == "data_type", unmapped.gaps
    assert _type(unmapped, table, column) != _type(mapped, table, column)
    assert "emitted as" in gaps[0].detail, gaps[0].detail


# --- Identity columns ---------------------------------------------------------------

def _identity(export: ddl_export.DdlExport, table: str, column: str) -> tuple[bool, int, int] | None:
    found = _column(export, table, column).find(exp.GeneratedAsIdentityColumnConstraint)
    if found is None:
        return None
    return bool(found.this), int(found.args["start"].name), int(found.args["increment"].name)


def test_sql_server_identity_keeps_its_seed_and_increment_by_default() -> None:
    export = _export(_mapping_case("tsql"), "tsql")
    assert _identity(export, "Ledger", "LedgerID") == (False, 100000, 5)
    assert _identity(export, "Batch", "BatchID") == (False, 1, 1)
    assert _gaps_naming(export, "Ledger", "LedgerID") == []


def test_oracle_identity_on_an_integer_is_by_default_and_always_is_named() -> None:
    export = _export(_mapping_case("oracle"), "oracle")
    assert _identity(export, "TICKETS", "TICKET_ID") == (False, 7, 3)
    [gap] = _gaps_naming(export, "TICKETS", "TICKET_ID")
    assert gap.kind == "identity" and "GENERATED ALWAYS" in gap.detail


def test_oracle_identity_on_number_is_a_named_sequence_default_with_its_seed() -> None:
    export = _export(_mapping_case("oracle"), "oracle")
    column = _column(export, "ACCOUNTS", "ACCOUNT_ID")
    assert column.find(exp.GeneratedAsIdentityColumnConstraint) is None
    default = column.find(exp.DefaultColumnConstraint).this.sql("postgres")
    assert default == "NEXTVAL('accounts_account_id_seq')"
    assert "CREATE SEQUENCE accounts_account_id_seq START WITH 393 INCREMENT BY 1" in export.statements
    assert export.statements.index("CREATE SEQUENCE accounts_account_id_seq START WITH 393 INCREMENT BY 1") < next(
        i for i, s in enumerate(export.statements) if '"ACCOUNTS"' in s[:40]), "the sequence comes before its table"
    [gap] = _gaps_naming(export, "ACCOUNTS", "ACCOUNT_ID")
    assert gap.kind == "identity" and "smallint, integer or bigint" in gap.detail and "ON NULL" in gap.detail


def test_a_column_an_oracle_trigger_fills_is_a_named_gap() -> None:
    model = _mapping_case("oracle")
    notes = next(e for e in model.entities if e.entity_name == "NOTES")
    identity = next(c for c in notes.columns if c.name == "NOTE_ID").identity
    assert identity is not None and (identity.kind, identity.trigger, identity.sequence) == (
        "trigger", "NOTES_BI", "NOTES_SEQ")
    export = _export(model, "oracle")
    [gap] = _gaps_naming(export, "NOTES", "NOTE_ID")
    assert gap.kind == "identity" and "NOTES_BI" in gap.detail and "NOTES_SEQ" in gap.detail
    assert _column(export, "NOTES", "NOTE_ID").find(exp.DefaultColumnConstraint) is None


def test_an_identity_for_another_target_is_named_not_dropped() -> None:
    export = ExporterService(source_dialect="tsql").generate_ddl_export(_mapping_case("tsql"), "snowflake")
    assert {g.detail.split(" ", 1)[0] for g in export.gaps if g.kind == "identity"} == {"LedgerID", "BatchID"}


# --- Sequences ----------------------------------------------------------------------

def test_a_postgresql_sequence_is_created_and_its_default_kept() -> None:
    model = _mapping_case("postgres")
    assert [s.model_dump() for s in model.sequences] == [{
        "name": "public.invoice_no_seq", "start": 1000, "increment": 5, "min_value": 1000,
        "max_value": 999999, "cache": 1, "cycle": False}]
    export = _export(model, "postgres")
    assert export.statements[0] == ("CREATE SEQUENCE public.invoice_no_seq START WITH 1000 INCREMENT BY 5 "
                                    "MINVALUE 1000 MAXVALUE 999999 CACHE 1")
    default = _column(export, "invoice", "invoice_no").find(exp.DefaultColumnConstraint)
    assert default is not None and "invoice_no_seq" in default.sql("postgres")
    assert export.gaps == []


def test_negative_control_without_the_sequence_the_default_is_a_named_gap() -> None:
    model = _mapping_case("postgres")
    model.sequences = []
    export = _export(model, "postgres")
    assert _column(export, "invoice", "invoice_no").find(exp.DefaultColumnConstraint) is None
    assert [g.kind for g in export.gaps] == ["default"]


def test_an_oracle_sequence_is_named_not_created() -> None:
    export = _export(_mapping_case("oracle"), "oracle")
    assert [g.detail for g in export.gaps if g.kind == "sequence"] == [
        ("APP.NOTES_SEQ: not emitted; sequences are created only for a PostgreSQL model exported to PostgreSQL "
         "(oracle to postgres)")]
    assert not any("NOTES_SEQ" in s for s in export.statements)


# --- Every identity and sequence the file declares is emitted or named ---------------
#
# Counted from the file's own text by patterns that share nothing with the
# importer, then compared with what the export states. An importer that loses
# one (as it did before this step, silently) fails here.

_SOURCE_IDENTITY = {"tsql": re.compile(r"\bIDENTITY\s*\(", re.IGNORECASE),
                    "oracle": re.compile(r"\bAS\s+IDENTITY\b", re.IGNORECASE),
                    "postgres": re.compile(r"\bAS\s+IDENTITY\b", re.IGNORECASE)}
_SOURCE_TRIGGER_FILL = re.compile(r"\.\s*NEXTVAL\s+INTO\s+:NEW\b|:NEW\s*\.\s*\S+\s*:=\s*\S+\s*\.\s*NEXTVAL",
                                  re.IGNORECASE)
_SOURCE_SEQUENCE = re.compile(r"^\s*CREATE\s+SEQUENCE\b", re.IGNORECASE | re.MULTILINE)

CASES = [("tsql", MAPPINGS / "tsql" / "type_mappings.sql"), ("oracle", MAPPINGS / "oracle" / "identity.sql"),
         ("postgres", MAPPINGS / "postgres" / "sequences.sql"), ("oracle", GENUINE / "oracle" / "co.sql"),
         ("tsql", GENUINE / "tsql" / "adventureworks.sql"), ("postgres", GENUINE / "postgres" / "pagila.sql")]


def _stated(export: ddl_export.DdlExport) -> tuple[int, int]:
    """(identity columns stated or named, sequences created or named) in an export.

    An identity column is stated as ``GENERATED … AS IDENTITY``, or by a
    sequence default standing in for it (a gap that says so), or named: filled
    by a trigger, or not emitted for the target. A note on an emitted identity
    (ALWAYS, ON NULL) is not a second one. A sequence is created, or named;
    the stand-ins' own sequences are not the file's.
    """
    trees = [sqlglot.parse_one(s, read="postgres") for s in export.statements if not s.startswith("CREATE EXTENSION")]
    emitted = sum(1 for t in trees for _ in t.find_all(exp.GeneratedAsIdentityColumnConstraint))
    details = [g.detail for g in export.gaps if g.kind == "identity"]
    stand_ins = sum(1 for d in details if "emitted as DEFAULT nextval" in d)
    named = sum(1 for d in details if "is filled on insert by trigger" in d or ": not emitted for " in d)
    created = sum(1 for t in trees if isinstance(t, exp.Create) and str(t.args.get("kind")).upper() == "SEQUENCE")
    return emitted + stand_ins + named, created - stand_ins + sum(1 for g in export.gaps if g.kind == "sequence")


def _declared(dialect: str, path: Path) -> tuple[int, int]:
    body = path.read_text(encoding="utf-8")
    return (len(_SOURCE_IDENTITY[dialect].findall(body)) + len(_SOURCE_TRIGGER_FILL.findall(body)),
            len(_SOURCE_SEQUENCE.findall(body)))


@pytest.mark.parametrize(("dialect", "path"), CASES, ids=[p.stem for _, p in CASES])
def test_every_identity_and_sequence_is_emitted_or_named(dialect: str, path: Path) -> None:
    declared = _declared(dialect, path)
    assert sum(declared) > 0, "fixture sanity: the file declares something to count"
    export = _export(_import(dialect, path), dialect)
    assert _stated(export) == declared, (path.name, _stated(export), declared)


def test_negative_control_an_importer_that_loses_identity_fails_the_count(monkeypatch: pytest.MonkeyPatch) -> None:
    """The importer as it was before this step: every identity property dropped."""
    read_column = importer._Builder._column

    def losing_identity(self: importer._Builder, table: importer._Table, item: exp.ColumnDef,
                        statement: object) -> None:
        read_column(self, table, item, statement)  # type: ignore[arg-type]
        table.columns[item.name].identity = None

    monkeypatch.setattr(importer._Builder, "_column", losing_identity)
    path = MAPPINGS / "tsql" / "type_mappings.sql"
    assert _stated(_export(_import("tsql", path), "tsql")) != _declared("tsql", path)


def test_negative_control_an_importer_that_skips_sequences_fails_the_count(monkeypatch: pytest.MonkeyPatch) -> None:
    path = MAPPINGS / "postgres" / "sequences.sql"
    monkeypatch.setattr(importer, "_CREATE_SEQUENCE", re.compile(r"(?!)"))
    export = _export(_import("postgres", path), "postgres")
    assert _stated(export) != _declared("postgres", path)


# --- Stored and reopened: through the real persistence path, read back raw ----------

@pytest_asyncio.fixture
async def session() -> AsyncIterator[AsyncSession]:
    engine = make_test_engine()
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    maker = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    async with maker() as sess:
        yield sess
    await engine.dispose()


async def test_identity_and_sequences_are_stored_and_reopened(session: AsyncSession) -> None:
    model = _mapping_case("oracle")
    workspace = Workspace(name="mappings")
    session.add(workspace)
    await session.flush()
    row = DataModel(workspace_id=workspace.workspace_id, title="mappings", target_dialect="oracle",
                    current_paradigm="3NF", sequences=[s.model_dump() for s in model.sequences] or None)
    session.add(row)
    await session.flush()
    await GraphRepository(session).replace_graph(row.model_id, model.entities, model.relationships)
    await session.commit()

    # Read from outside the ORM: the stored JSON itself.
    stored = (await session.execute(text(
        "SELECT c.column_name, c.identity FROM entity_columns c JOIN model_entities e ON e.entity_id = c.entity_id "
        "WHERE e.model_id = :m AND c.identity IS NOT NULL ORDER BY c.column_name").bindparams(
            bindparam("m", type_=Uuid)), {"m": row.model_id})).all()
    assert [name for name, _ in stored] == ["ACCOUNT_ID", "NOTE_ID", "TICKET_ID"]

    reopened = await SynthesisEngine(session, None).get_model(row.model_id)  # type: ignore[arg-type]
    assert reopened is not None
    before = {(e.entity_name, c.name): c.identity for e in model.entities for c in e.columns}
    after = {(e.entity_name, c.name): c.identity for e in reopened.entities for c in e.columns}
    assert after == before
    assert reopened.sequences == model.sequences and [s.name for s in reopened.sequences] == ["APP.NOTES_SEQ"]


async def test_negative_control_a_model_saved_without_its_sequences_reopens_without_them(
    session: AsyncSession,
) -> None:
    model = _mapping_case("postgres")
    workspace = Workspace(name=f"w{uuid.uuid4().hex[:6]}")
    session.add(workspace)
    await session.flush()
    row = DataModel(workspace_id=workspace.workspace_id, title="no sequences", target_dialect="postgres",
                    current_paradigm="3NF")
    session.add(row)
    await session.flush()
    await GraphRepository(session).replace_graph(row.model_id, model.entities, model.relationships)
    await session.commit()
    reopened = await SynthesisEngine(session, None).get_model(row.model_id)  # type: ignore[arg-type]
    assert reopened is not None and reopened.sequences == [] and model.sequences
